**Задание 1**

​
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [111]:
import numpy as np
a = np.arange(5)[::-1]
a

array([4, 3, 2, 1, 0])

In [14]:
type(a)

numpy.ndarray

**Задание 2**

​
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
​

In [42]:
z = np.diag(np.arange(0, 7)[::-1])
z

array([[6, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [48]:
summ = 0
for i in range (0, 7):
    summ += z[i][i]
print(summ)

21


**Задание 3**

​
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.


In [131]:
import pandas as pd
ratings = pd.read_table('ml-1m/ratings.dat', names = ['UserID', 'MovieID', 'Rating', 'Timestamp'], sep = '::', header=0)
movies = pd.read_table('ml-1m/movies.dat', names = ['MovieID', 'Title', 'Genre'], sep = '::', header=0)
joined = ratings.merge(movies, on='MovieID', how='left')
filtered_data = joined[ (joined['Rating']==5) ]
filtered_data.groupby('Title').count().sort_values('Rating', ascending=False).head(1)


D:\anaconda\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  
D:\anaconda\lib\site-packages\ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until


UserID  MovieID  Rating  Timestamp  Genre
Title                                                            
American Beauty (1999)    1963     1963    1963       1963   1963

**Задание 4**

​
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.
​

In [132]:
data = pd.read_csv('power.csv')
f1 = data[ ((data['country']=='Latvia') | (data['country']=='Estonia') | (data['country']=='Lithuania'))]
f2 = f1[ ((f1['category']==4) | (f1['category']==12)| (f1['category']==21)) ]
f3 = f2[ (f2['quantity']>0) ]
filtered_countries = f3[ ((f3['year']>2004) & (f3['year']<2011)) ]
filtered_countries['quantity'].sum()

240580.0

**Задание 5**

​
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [112]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [113]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True