**Задание 1**

​
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [111]:
import numpy as np
a = np.arange(5)[::-1]
a

array([4, 3, 2, 1, 0])

In [14]:
type(a)

numpy.ndarray

**Задание 2**

​
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
​

In [42]:
z = np.diag(np.arange(0, 7)[::-1])
z

array([[6, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [48]:
summ = 0
for i in range (0, 7):
    summ += z[i][i]
print(summ)

21


**Задание 3**

​
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.


In [110]:
import pandas as pd
ratings = pd.read_table('ml-1m/ratings.dat', names = ['UserID', 'MovieID', 'Rating', 'Timestamp'], sep = '::', header=0)
movies = pd.read_table('ml-1m/movies.dat', names = ['MovieID', 'Title', 'Genre'], sep = '::', header=0)
joined = ratings.merge(movies, on='MovieID', how='left')
filtered_data = joined[ (joined['Rating']==5) ]
filtered_data.groupby('Title').count().sort_values('Rating', ascending=False).head()


D:\anaconda\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  
D:\anaconda\lib\site-packages\ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until


UserID  MovieID  Rating  \
Title                                                                         
American Beauty (1999)                                1963     1963    1963   
Star Wars: Episode IV - A New Hope (1977)             1826     1826    1826   
Raiders of the Lost Ark (1981)                        1500     1500    1500   
Star Wars: Episode V - The Empire Strikes Back ...    1483     1483    1483   
Godfather, The (1972)                                 1475     1475    1475   

                                                    Timestamp  Genre  
Title                                                                 
American Beauty (1999)                                   1963   1963  
Star Wars: Episode IV - A New Hope (1977)                1826   1826  
Raiders of the Lost Ark (1981)                           1500   1500  
Star Wars: Episode V - The Empire Strikes Back ...       1483   1483  
Godfather, The (1972)                                    1475   1475

**Задание 4**

​
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.
​

In [130]:
data = pd.read_csv('power.csv')
f1 = data[ ((data['country']=='Latvia') | (data['country']=='Estonia') | (data['country']=='Lithuania'))]
f2 = f1[ ((f1['category']==4) | (f1['category']==12)| (f1['category']==21)) ]
f3 = f2[ (f2['quantity']>0) ]
filtered_countries = f3[ ((f3['year']>2004) & (f3['year']<2011)) ]
filtered_countries

country  year  quantity  category
10617     Estonia  2008       1.0         4
10620     Estonia  2005       1.0         4
11156   Lithuania  2008       1.0         4
11158   Lithuania  2006       1.0         4
11159   Lithuania  2005       1.0         4
12755     Estonia  2008       1.0         4
12758     Estonia  2005       1.0         4
13294   Lithuania  2008       1.0         4
13296   Lithuania  2006       1.0         4
13297   Lithuania  2005       1.0         4
15525     Estonia  2008       1.0         4
15528     Estonia  2005       1.0         4
16068   Lithuania  2008       1.0         4
16070   Lithuania  2006       1.0         4
16071   Lithuania  2005       1.0         4
17675     Estonia  2008       1.0         4
17678     Estonia  2005       1.0         4
18218   Lithuania  2008       1.0         4
18220   Lithuania  2006       1.0         4
18221   Lithuania  2005       1.0         4
19854     Estonia  2008       1.0         4
19856     Estonia  2006       3.0         4
19857     Estonia  2005       6.0         4
20511   Lithuania  2008       1.0         4
20513   Lithuania  2006       1.0         4
20514   Lithuania  2005       1.0         4
21902     Estonia  2006       3.0         4
21903     Estonia  2005       5.0         4
25743     Estonia  2008       1.0         4
25746     Estonia  2005       1.0         4
...           ...   ...       ...       ...
248555     Latvia  2005    2166.0        21
248672  Lithuania  2010    3768.0        21
248673  Lithuania  2009    4909.0        21
248674  Lithuania  2008    4655.0        21
248675  Lithuania  2007    4613.0        21
248676  Lithuania  2006    4587.0        21
248677  Lithuania  2005    4556.0        21
251648  Lithuania  2009    1183.0        21
251649  Lithuania  2008    1183.0        21
251650  Lithuania  2007    1183.0        21
251651  Lithuania  2006    1183.0        21
251652  Lithuania  2005    1183.0        21
253561    Estonia  2010     108.0        21
253562    Estonia  2009     104.0        21
253563    Estonia  2008      77.0        21
253564    Estonia  2007      50.0        21
253565    Estonia  2006      31.0        21
253566    Estonia  2005      31.0        21
253962     Latvia  2010      32.0        21
253963     Latvia  2009      32.0        21
253964     Latvia  2008      28.0        21
253965     Latvia  2007      26.0        21
253966     Latvia  2006      27.0        21
253967     Latvia  2005      27.0        21
253981  Lithuania  2010     133.0        21
253982  Lithuania  2009      98.0        21
253983  Lithuania  2008      54.0        21
253984  Lithuania  2007      47.0        21
253985  Lithuania  2006      31.0        21
253986  Lithuania  2005       1.0        21

[347 rows x 4 columns]

**Задание 5**

​
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [112]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [113]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True